config/routes.rb
Kwhite17IsraShabirIsabellatrombaProj3::Application.routes.draw do
  get "members/index"

  get "members/show"
  
  get "group_purchases/:group_purchase_id/invoices/find_members" => 'invoices#find_members', :as => :find_members

  devise_for :members

  resources :group_purchases do
    resources :invoices
  end

  resources :payment_accounts do
    member do
      post :transfer
    end
  end

  root to: 'members#index'

end

app/controllers/group_purchases_controller.rb
class GroupPurchasesController < ApplicationController
  # GET /group_purchases
  # GET /group_purchases.json
  def index
    #puts params
    #@group_purchases = GroupPurchase.all
    respond_to do |format|
      format.html {redirect_to members_index_path, notice: 'Link prohibited.'}
      format.json { render json: @group_purchases }
    end
  end

  # GET /group_purchases/1
  # GET /group_purchases/1.json
  def show
    @group_purchase = GroupPurchase.find(params[:id])
    puts 'grouppurchase id'
    puts @group_purchase.id
    @debtors = @group_purchase.debtors
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group_purchase }
    end
  end

  # GET /group_purchases/new
  # GET /group_purchases/new.json
  def new
    @group_purchase = GroupPurchase.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group_purchase }
    end
  end

  # GET /group_purchases/1/edit
  def edit
    @group_purchase = GroupPurchase.find(params[:id])
  end

  # POST /group_purchases
  # POST /group_purchases.json
  def create
    @group_purchase = GroupPurchase.new(params[:group_purchase])
    @group_purchase.creatorName = current_member.email
    @group_purchase.creditor = current_member
    respond_to do |format|
      if @group_purchase.save
        format.html { redirect_to @group_purchase, notice: 'Group purchase was successfully created.' }
        format.json { render json: @group_purchase, status: :created, location: @group_purchase }
      else
        format.html { render action: "new" }
        format.json { render json: @group_purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /group_purchases/1
  # PUT /group_purchases/1.json
  def update
    @group_purchase = GroupPurchase.find(params[:id])

    respond_to do |format|
      if @group_purchase.update_attributes(params[:group_purchase])
        format.html { redirect_to @group_purchase, notice: 'Group purchase was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group_purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_purchases/1
  # DELETE /group_purchases/1.json
  def destroy
    @group_purchase = GroupPurchase.find(params[:id])
    @group_purchase.destroy
    redirect_to members_index_path

    # respond_to do |format|
    #   format.html { redirect_to members_index_path }
    #   format.json { head :no_content }
  end
end

app/helpers/group_purchases_helper.rb
module GroupPurchasesHelper
end

app/views/group_purchases/_form.html.erb
<%= form_for(@group_purchase) do |f| %>
  <% if @group_purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group_purchase.errors.count, "error") %> prohibited this group_purchase from being saved:</h2>

      <ul>
      <% @group_purchase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Purchase Name" %><br />
    <%= f.text_field :purchaseName %>
  </div>
  <br />
  <div class="field">
    <%= f.label :balance %><br />
    <%= f.number_field :balance , :step=>".01", :max=>"100000", :min=>"0"%>
  </div>
  <div class="actions">
    <%= f.submit "Create Group Purchase", :class=>"btn" %>
  </div>
<% end %>

app/views/group_purchases/edit.html.erb
<h1>Editing group_purchase</h1>

<%= render 'form' %>

<%= link_to 'Show', @group_purchase %> |
<%= link_to 'Back', group_purchases_path %>

app/views/group_purchases/index.html.erb
<h1>Listing group_purchases</h1>
<table>
  <tr>
    <td> Balance</td>
    <td><%=@group_purchase.balance%></td>
  </tr>
</table>
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @group_purchase.members.each do |member| %>
  <tr>
    <td><%=member.email%></td>
    <td><%=member.balance%></td>
    <td><%= link_to 'Destroy', controller: "invoices", action: "destroy", id: Invoice.where(name: member.email).first, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add a member', new_invoice_path %>

app/views/group_purchases/new.html.erb
<h1>New Purchase</h1>

<%= render 'form' %>

<%= link_to 'Back', members_index_path %>

app/views/group_purchases/show.html.erb
<p>
  <b>Name:</b>
  <%= @group_purchase.purchaseName %>
</p>

<p>
  <b>Balance:</b>
  <%= @group_purchase.balance %>
</p>

<p>
  <b>Number of Members:</b>
  <%= @num_debtors %>
</p>
<p>
	<b>Creditor:</b>
	<%= @group_purchase.creditor.email%></li>
</p>
<p>
	<b>Debtors:</b>
	<ul>
		<% @debtors.each do |debtor| %>
			<li><%=debtor.email%></li>
		<% end %>
	</ul>
</p>

<%= link_to 'Add a Debitor', new_group_purchase_invoice_path(@group_purchase) %> |
<%= link_to 'Return to Personal Page', members_index_path %> |
<%= link_to 'Delete Purchase', @group_purchase, method: :delete, data: {confirm: 'Are you sure'} %>