config/routes.rb
Kwhite17IsraShabirIsabellatrombaProj3::Application.routes.draw do
  get "members/index"

  get "members/show"
  
  get "group_purchases/:group_purchase_id/invoices/find_members" => 'invoices#find_members', :as => :find_members

  devise_for :members

  resources :group_purchases do
    resources :invoices
  end

  resources :payment_accounts do
    member do
      post :transfer
    end
  end

  root to: 'members#index'

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <% if member_signed_in? %>
    <li>
    <%= link_to('Logout', destroy_member_session_path, :method=>'delete') %>
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_member_session_path)  %>
    </li>
  <% end %>
  <% if member_signed_in? %>
    <li>
    <%= link_to('Edit User Account', edit_member_registration_path) %>
    </li>
    <li>
    <%= link_to('Payment Account', edit_payment_account_path(@payment_account)) %>
    </li>
  <% else %>
    <li>
    <%= link_to('Sign up', new_member_registration_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Bootstrap" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
  </body>
</html>