config/routes.rb
Kwhite17IsraShabirIsabellatrombaProj3::Application.routes.draw do
  get "members/index"

  get "members/show"
  
  get "group_purchases/:group_purchase_id/invoices/find_members" => 'invoices#find_members', :as => :find_members

  devise_for :members

  resources :group_purchases do
    resources :invoices
  end

  resources :payment_accounts do
    member do
      post :transfer
    end
  end

  root to: 'members#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :invoices, :foreign_key=>"debtor_id"
  has_many :group_purchases, :through=> :invoices
  has_many :created_group_purchases, :class_name=>"GroupPurchase", :foreign_key=> "creditor_id"
  has_one  :payment_account

  def self.search(search)
    if search
      where('email LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

  def paid_invoices
    self.invoices.select { |inv| inv.paid }
  end

  def unpaid_invoices
    self.invoices.select { |inv| not inv.paid }
  end


end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_filter :authenticate_member!
  def index
  	if member_signed_in?
      puts current_member.email
  		@purchases_creditor = current_member.created_group_purchases
      @invoices_debitor = current_member.unpaid_invoices
      @invoices_debited = current_member.paid_invoices
      @payment_account  = current_member.payment_account
  	end
  end

  def show
    @purchases_creditor = current_member.created_group_purchases
    @invoices_debitor = current_member.invoices
  	respond_to do |format|
  		format.html
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/index.html.erb
<div class="jumbotron">
  <% if member_signed_in? %>
    <%= link_to "Create New Purchase", new_group_purchase_path, :class=>"btn btn-primary"%>

    <h3>Money Owed to You</h3>
    <table class="table">
      <th>Purchase Name</th>
      <th>Balance</th>
      <% @purchases_creditor.each do |purchase| %>
        <tr>
          <td><%=link_to purchase.purchaseName,group_purchase_path(purchase)%></td>
          <td><%=purchase.balance%></td>
        </tr>
      <%end%>
    </table>

    <h3>Money You Owe</h3>
    <table class="table">
      <th>Purchase Name</th>
      <th>Balance</th>
        <% @invoices_debitor.each do |invoice| %>
        <tr>
          <td><%= invoice.group_purchase.purchaseName %></td>
          <td><%=invoice.balance%></td>
          <td><%= link_to "Pay", transfer_payment_account_path(id: @payment_account.id, invoice_id: invoice.id), method: :post, class: "btn-primary, btn-large" %></td>
        </tr>
      <%end%>
    </table>

    <h3>Money You Paid</h3>
    <table class="table">
      <th>Purchase Name</th>
      <th>Balance</th>
        <% @invoices_debited.each do |invoice| %>
        <tr>
          <td><%= invoice.group_purchase.purchaseName %></td>
          <td><%=invoice.balance%></td>
        </tr>
      <%end%>
    </table>

  <% else %>
    <h1>Welcome, new user!</h1>
    <p class="lead">
      You must sign in or sign up before you can access our super sweet,
      top secret content.
    </p>
    <div class="row-fluid">
      <div class="span6">
        <%= link_to "Sign In", new_member_session_path, :class => "btn btn-success" %>
      </div>
      <div class="span6">
        <%= link_to "Sign Up", new_member_registration_path, :class => "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>
<%#= link_to invoice.balance, group_purchase_invoice_path(purchase, invoice) %>

app/views/members/show.html.erb
<h1>Money Owed to You</h1>
<table>
	<th>Purchase Name</th>
	<th>Balance</th>
	<%= @purchases_creditor.each do |purchase| %>
		<tr>
			<td><%=purchase.purchaseName%></td>
			<td><%=purchase.balance%></td>
	</tr>
	<%end%>
</table>

<h1>Money You Owe</h1>
<table>
	<th>Purchase</th>
	<th>Balance</th>
	<%=@purchases_debitor.each do |purchase| %>
		<tr>
			<td><%=purchase.purchaseName%></td>
			<td><%=purchase.balance%></td>
		</tr>
	<%end%>
</table>

<%= link_to "Create New Purchase", new_group_purchase_path%>